services:
  db:
    image: postgres:16
    container_name: crud-backend-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: crud_backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - crud_backend_pgdata:/var/lib/postgresql/data

volumes:
  crud_backend_pgdata:
