spring.application.name=crud-backend
# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/crud_backend
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=claveSuperSecretaParaJWTqueDebeSerLargaMinimo256bits1234567890
jwt.expiration=86400000
